# Generated by Django 5.1.4 on 2025-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workoutlog_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
